// <auto-generated />
using Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dados.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210824192211_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidades.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GeneroBiologico")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("PorteAnimal")
                        .HasColumnType("int");

                    b.Property<int>("RacaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("ID");

                    b.HasIndex("Id")
                        .HasDatabaseName("I_Animais_Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("I_Animais_Nome");

                    b.HasIndex("RacaId")
                        .HasDatabaseName("I_Animais_RacaId");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("Dominio.Entidades.Raca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RacaID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PorteRaca")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Racas");

                    b.HasIndex("Id")
                        .HasDatabaseName("I_Racas_Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("I_Racas_Nome");

                    b.ToTable("Racas");
                });

            modelBuilder.Entity("Dominio.Entidades.Animal", b =>
                {
                    b.HasOne("Dominio.Entidades.Raca", "Raca")
                        .WithMany("Animais")
                        .HasForeignKey("RacaId")
                        .HasConstraintName("FK_Animal_RacaIdXRaca_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("Dominio.Entidades.Raca", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
